In [1]:
## Import Library(s)
import pandas as pd

In [57]:
## Question 1
## Read in survey_results_public.csv from 2022 Stack Overflow Survey https://insights.stackoverflow.com/survey 
df = pd.read_csv("survey_results_public.csv")
df.head()

,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,YearsCode,...,TimeSearching,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly
0,1,None of these,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,I am a developer by profession,"Employed, full-time",Fully remote,Hobby;Contribute to open-source projects,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Difficult,NaN
2,3,"I am not primarily a developer, but I write co...","Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,NaN,14,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult,40205.0
3,4,I am a developer by profession,"Employed, full-time",Fully remote,I don’t code outside of work,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Books / Physical media;School (i.e., Universit...",NaN,NaN,20,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Appropriate in length,Easy,215232.0
4,5,I am a developer by profession,"Employed, full-time","Hybrid (some remote, some in-person)",Hobby,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Other online resources (e.g., videos, blogs, f...",Technical documentation;Blogs;Stack Overflow;O...,NaN,8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Too long,Easy,NaN

In [58]:
## Question 2
## Print out MainBranch types and their frequency
freq_dict = {}
for i in df["MainBranch"].unique():
    freq_dict[i] = 0

for i in df["MainBranch"]:
    if i in freq_dict.keys():
        freq_dict[i] += 1

freq_dict

{'None of these': 1497,
 'I am a developer by profession': 53507,
 'I am not primarily a developer, but I write code sometimes as part of my work': 5794,
 'I code primarily as a hobby': 4865,
 'I am learning to code': 6309,
 'I used to be a developer by profession, but no longer am': 1296}

In [59]:
## Question 3
## Print out the length of your filtered list
max_key = ""
for key, value in freq_dict.items():
    if value == max(freq_dict.values()):
        max_key = key

df_most_responses = df[df["MainBranch"] == max_key]
df_most_responses.shape[0]

53507

In [60]:
## Question 4
## Print out the database types and their frequency
databases = []
for i in df_most_responses["DatabaseHaveWorkedWith"]:
    split_str = str(i).split(";")
    databases.extend(split_str)

database_count = dict((key,0) for key in set(databases))

for i in df_most_responses["DatabaseHaveWorkedWith"]:
    split_str = str(i).split(";")
    for i in split_str:
        database_count[i] += 1

database_count

{'nan': 6267,
 'Elasticsearch': 6642,
 'Cassandra': 1306,
 'Neo4j': 1016,
 'MariaDB': 8561,
 'Couchbase': 615,
 'SQLite': 14733,
 'PostgreSQL': 22214,
 'MongoDB': 13518,
 'MySQL': 21830,
 'Microsoft SQL Server': 13750,
 'Cloud Firestore': 3478,
 'Redis': 11935,
 'IBM DB2': 944,
 'Oracle': 5632,
 'Firebase Realtime Database': 4094,
 'DynamoDB': 4504,
 'CouchDB': 638}

In [63]:
## Question 5 
## Create new column 'DBHWW_Count', sort and print out the count of the first record
df_most_responses = df_most_responses.reset_index()
df_most_responses["DBHWW_Count"] = 0
for idx, i in enumerate(df_most_responses["DatabaseHaveWorkedWith"]):
    split_str = str(i).split(";")
    df_most_responses.loc[df_most_responses.index==idx, "DBHWW_Count"] = len(split_str)

df_most_responses = df_most_responses.sort_values("DBHWW_Count", ascending=False)
df_most_responses.head(1)

,index,ResponseId,MainBranch,Employment,RemoteWork,CodingActivities,EdLevel,LearnCode,LearnCodeOnline,LearnCodeCoursesCert,...,TimeAnswering,Onboarding,ProfessionalTech,TrueFalse_1,TrueFalse_2,TrueFalse_3,SurveyLength,SurveyEase,ConvertedCompYearly,DBHWW_Count
26833,36201,36202,I am a developer by profession,"Employed, full-time;Student, full-time;Student...","Hybrid (some remote, some in-person)",I don’t code outside of work,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Books / Physical media;Friend or family member...,Technical documentation;Blogs;Programming Game...,Coursera;Udemy;Codecademy;Pluralsight;edX;Udac...,...,Over 120 minutes a day,Just right,Innersource initiative;DevOps function;Microse...,Yes,Yes,Yes,Appropriate in length,Neither easy nor difficult,NaN,17

In [72]:
## Question 6 
## Write  the first 10 rows as a TSV named '<student-first-intial><student-last-name>-module2.tsv' (insert your first and last name)
## Only include the following columns: ['ResponseId','MainBranch','DatabaseHaveWorkedWith','DBHWW_Count'] 
df_most_responses[['ResponseId','MainBranch','DatabaseHaveWorkedWith','DBHWW_Count']].iloc[:10,:].to_csv(r"G:\My Drive\JHU Data Science Masters\Data Engineering Principles and Practice\Module 2\ZHatzenbeller-module2.tsv", sep="\t")